apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-agent-config
  namespace: local-ai-agent
  labels:
    app: local-ai-agent
data:
  # Application Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Database Configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "ai_agent_db"
  
  # JWT Configuration
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "30"
  
  # Rate Limiting
  RATE_LIMIT_ENABLED: "true"
  DEFAULT_RATE_LIMIT_PER_MINUTE: "100"
  DEFAULT_RATE_LIMIT_PER_HOUR: "1000"
  
  # Monitoring
  METRICS_ENABLED: "true"
  HEALTH_CHECK_ENABLED: "true"