apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-secrets
  namespace: local-ai-agent
  labels:
    app: local-ai-agent
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # To encode: echo -n "your-secret" | base64
  
  # JWT Secret Key (replace with strong random key)
  JWT_SECRET_KEY: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24tYmFzZTY0LWVuY29kZWQ=
  
  # Database credentials
  DATABASE_USER: YWlhZ2VudA==  # aiagent
  DATABASE_PASSWORD: c2VjdXJlUGFzc3dvcmQxMjM=  # securePassword123
  
  # Redis password (if authentication enabled)
  REDIS_PASSWORD: cmVkaXNQYXNzd29yZA==  # redisPassword
  
  # Additional secrets
  ENCRYPTION_KEY: ZW5jcnlwdGlvbktleTEyMzQ1Ng==  # encryptionKey123456
  
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: local-ai-agent
  labels:
    app: local-ai-agent
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials if using private registry
  # .dockerconfigjson: <base64-encoded-docker-config>